language: cpp
os: linux
compiler: gcc
dist: xenial

addons:
  apt:
    # Get new gcc
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

before_install:
    # Add repository for Qt
    - sudo apt-add-repository --yes ppa:beineri/opt-qt-5.10.1-xenial
    - sudo apt-get -qq update

    # Decrypt auth token for deployment
    - '[ "$TRAVIS_SECURE_ENV_VARS" == "false" ] || openssl aes-256-cbc -K $encrypted_e533d41baef3_key -iv $encrypted_e533d41baef3_iv -in deployment/.dropbox_uploader.enc -out ~/.dropbox_uploader -d'

install:
    # Install needed Qt modules and libraries for qt
    - sudo apt-get --yes install libgl1-mesa-dev qt510base qt510svg qt510script

    # Set Qt variables
    - QTDIR="/opt/qt510"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt510/bin/qt510-env.sh

    # Set used gcc version
    - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
    - export CC=gcc-7
    - export CXX=g++-7

before_script:
    # Clone atools
    - git clone --branch=master https://github.com/albar965/atools.git ../atools

    # Get atools if auth token for dropbox is available
    - '[ -f ~/.dropbox_uploader ] && ../littlexpconnect/deployment/dropbox_uploader.sh download linux/atools-release.tar.gz ../atools-release.tar.gz'
    - '[ -f ~/.dropbox_uploader ] && tar -xvzf ../atools-release.tar.gz -C ../'

script:
    # Build atools if auth token for dropbox is not available
    - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" ] || mkdir ../build-atools-release'
    - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" ] || cd ../build-atools-release'
    - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" ] || qmake ../atools/atools.pro CONFIG+=release'
    - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" ] || make -j2'

    # Build littlexpconnect
    - mkdir ../build-littlexpconnect-release
    - cd ../build-littlexpconnect-release
    - qmake ../littlexpconnect/littlexpconnect.pro CONFIG+=release
    - make -j2

after_success:
    # Deploy artefacts to dropbox
    - tar -cvzf ../littlexpconnect-release.tar.gz ../build-littlexpconnect-release/
    - '[ -f ~/.dropbox_uploader ] && ../littlexpconnect/deployment/dropbox_uploader.sh delete linux/littlexpconnect-release.tar.gz'
    - '[ -f ~/.dropbox_uploader ] && ../littlexpconnect/deployment/dropbox_uploader.sh mkdir linux'
    - '[ -f ~/.dropbox_uploader ] && ../littlexpconnect/deployment/dropbox_uploader.sh upload ../littlexpconnect-release.tar.gz linux'

